// <auto-generated />
namespace GesarUretimTakip.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _21102023 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_21102023));
        
        string IMigrationMetadata.Id
        {
            get { return "202310211357049_21102023"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
